createCRUD('/employees', 'employeeDatabase.json', 'employees', [
    ['name', check('name').exists().withMessage('name must be provided').isLength({min : 1, max : 20}).withMessage('name must be between 1 to 20 chars')],
    ['father', check('father').exists().withMessage('father must be provided').isLength({min : 1, max : 20}).withMessage('father must be between 1 to 20 chars')],
    ['mother', check('mother').exists().withMessage('mother must be provided').isLength({min : 1, max : 20}).withMessage('mother must be between 1 to 20 chars')],
    ['present_address', check('present_address').exists().withMessage('present_address must be provided').isLength({min : 1, max : 50}).withMessage('present_address must be between 1 to 20 chars')],
    ['permanent_address', check('permanent_address').exists().withMessage('permanent_address must be provided').isLength({min : 1, max : 50}).withMessage('permanent_address must be between 1 to 20 chars')],
    ['academic_achievement', check('academic_achievement').exists().withMessage('academic_achievement must be provided').isLength({min : 1, max : 50}).withMessage('academic_achievement must be between 1 to 20 chars')],
    ['languages_skills', check('languages_skills').exists().withMessage('languages_skills must be provided').isLength({min : 1, max : 30}).withMessage('languages_skills must be between 1 to 20 chars')],
    ['designation', check('designation').exists().withMessage('designation must be provided').isLength({min : 1, max : 20}).withMessage('designation must be between 1 to 20 chars')],
    ['contact_no', check('contact_no').exists().withMessage('contact_no must be provided').isLength({min : 1, max : 20}).withMessage('contact_no must be between 1 to 20 chars')],
    ['e_mail', check('e_mail').exists().withMessage('e_mail must be provided').isLength({min : 1, max : 20}).withMessage('e_mail must be between 1 to 20 chars')],
    ['room_no', check('room_no').exists().withMessage('room_no must be provided').isLength({min : 1, max : 20}).withMessage('room_no must be between 1 to 20 chars')],
    ['image', check('image').exists().withMessage('image must be provided').isLength({min : 1, max : 20}).withMessage('image must be between 1 to 20 chars')],
    ['nationality', check('nationality').exists().withMessage('nationality must be provided').isLength({min : 1, max : 20}).withMessage('nationality must be between 1 to 20 chars')],
    ['brith', check('brith').exists().withMessage('brith must be provided').isLength({min : 1, max : 20}).withMessage('brith must be between 1 to 20 chars')],
    ['nid', check('nid').exists().withMessage('nid must be provided').isLength({min : 1, max : 20}).withMessage('nid must be between 1 to 20 chars')],
]);